### ISSUE TITLE
按照readme以及b站教程还是出现问题。 UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence

### ISSUE THREAD

**Issue by WThirteen** [justld/dofaker#7]
一开始以为是python版本的问题，查看b站后，重新创建了3.8的版本，并根据视频内容下载权重文件。
在cmd中 输入 python web_ui.py，报错如下：

Traceback (most recent call last):
  File "web_ui.py", line 3, in <module>
    import gradio as gr
  File "E:\Anaconda\Setup\envs\fake_face\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "E:\Anaconda\Setup\envs\fake_face\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "E:\Anaconda\Setup\envs\fake_face\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "E:\Anaconda\Setup\envs\fake_face\lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "E:\Anaconda\Setup\envs\fake_face\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in <module>
    class MultimodalTextbox(FormComponent):
  File "E:\Anaconda\Setup\envs\fake_face\lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "E:\Anaconda\Setup\envs\fake_face\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
  File "E:\Anaconda\Setup\envs\fake_face\lib\pathlib.py", line 1237, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence

求问哪里出现了问题

**Comment by WThirteen** [comment]
问题解决了，把gradio的版本改为4.8，可以运行出ui
似乎安装最新的版本有问题。
